# Generated by Django 4.1.1 on 2022-09-07 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=1000)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 9, 7, 11, 12, 28, 6019, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("image", models.ImageField(upload_to="post_images/")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "s",
            },
        ),
    ]
